site_name: doc.js
repo_url: https://github.com/chrisvm/doc.js
docs_dir: docs
site_dir: docs/html
theme: readthedocs
pages:
  - Home: index.md
  - Configuration: configuration.md
  - Overview: overview.md
